Add option to override root directory

diff --git a/bin/dynamic-colors b/bin/dynamic-colors
--- a/bin/dynamic-colors
+++ b/bin/dynamic-colors
@@ -69,6 +69,23 @@ OSC="${ESC}]"
 colors=( background foreground cursor mouse_background mouse_foreground highlight border color0 color1 color2 color3 color4 color5 color6 color7 color8 color9 color10 color11 color12 color13 color14 color15 )
 color_names=( black red green yellow blue magenta cyan white brblack brred brgreen bryellow brblue brmagenta brcyan brwhite )
 
+while getopts ":o:" opt; do
+  case $opt in
+    o)
+      DYNAMIC_COLORS_ROOT="${OPTARG%/}"
+      shift; shift;
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires path to a dynamic-color folder" >&2
+      exit 1
+      ;;
+  esac
+done
+
 if [ -z "${DYNAMIC_COLORS_ROOT}" ]; then
   DYNAMIC_COLORS_ROOT="${HOME}/.dynamic-colors"
 else
