Handles switching to xcolors type files, no cycling yet. Optional custom xcolor folder via DYNAMIC_COLORS_THEMES

diff --git a/bin/dynamic-colors b/bin/dynamic-colors
--- a/bin/dynamic-colors
+++ b/bin/dynamic-colors
@@ -75,18 +75,24 @@ if [ -z "${DYNAMIC_COLORS_ROOT}" ]; then
 else
   DYNAMIC_COLORS_ROOT="${DYNAMIC_COLORS_ROOT%/}"
 fi
-COLORSCHEMES="${DYNAMIC_COLORS_ROOT}/colorschemes"
+
+if [ -z "${DYNAMIC_COLORS_THEMES}" ]; then
+  FOLDER="/colorschemes"
+  DYNAMIC_COLORS_THEMES=$DYNAMIC_COLORS_ROOT$FOLDER
+else
+  DYNAMIC_COLORS_THEMES="${DYNAMIC_COLORS_THEMES%/}"
+fi
 
 write_colorscheme_name () {
   echo "$1" > "${DYNAMIC_COLORS_ROOT}/colorscheme"
 }
 
 load_colorscheme_name () {
-  head -1 "${DYNAMIC_COLORS_ROOT}/colorscheme"
+  echo "$1" > "${DYNAMIC_COLORS_ROOT}/colorscheme"
 }
 
 init () {
-  [ ! -f "${DYNAMIC_COLORS_ROOT}/colorscheme" ] && return
+  [ ! -f "$DYNAMIC_COLORS_THEMES" ] && return
   colorscheme_name=$(load_colorscheme_name)
   load_colorscheme "$colorscheme_name"
   set_colors
@@ -105,66 +111,82 @@ set_colors () {
 }
 
 load_colorscheme () {
-  [ ! -f "$COLORSCHEMES/$1.sh" ] && die "error: unknown colorscheme '$1'"
-  . "$COLORSCHEMES/$1.sh" # source colorscheme file
+  [ ! -f "$DYNAMIC_COLORS_THEMES/$1" ] && die "error: unknown colorscheme '$1'"
+
+  colorschemeFile=`cat "$DYNAMIC_COLORS_THEMES/$1"`
+  hexRegex="(\#\S{3,6})"
+  groupRegex="(\w*)\:"
+
+  printf %s "$colorschemeFile" | while IFS= read -r line
+  do
+     if [[ $line =~ $groupRegex ]]; then
+       group="${BASH_REMATCH[1]}"
+     fi
+     if [[ $line =~ $hexRegex ]];then
+       hex="${BASH_REMATCH[1]}"
+     fi
+     change_color $group $hex
+  done
+  # ."$COLORSCHEMES/$1.sh" # source colorscheme file
 }
 
 switch () {
   write_colorscheme_name "$1"
   load_colorscheme "$1"
-  set_colors
+  # set_colors
 }
 
-audit () {
-  unset_colors
-  load_colorscheme "$1"
-  declare -a problems
-  for color in ${colors[@]}; do
-    if [ ! ${!color} ]; then
-      problems=( "${problems[@]}" "\033[4m$color\033[0m is not defined" )
-    fi
-  done
-  if [ ${#problems[@]} -ne 0 ]; then
-    echo >&2 "$1:"
-    for p in "${problems[@]}"
-    do
-      echo >&2 " * $p"
-    done
-    exit 1
-  fi
-}
+# TODO REMOVE
+# audit () {
+#   unset_colors
+#   load_colorscheme "$1"
+#   declare -a problems
+#   for color in ${colors[@]}; do
+#     if [ ! ${!color} ]; then
+#       problems=( "${problems[@]}" "\033[4m$color\033[0m is not defined" )
+#     fi
+#   done
+#   if [ ${#problems[@]} -ne 0 ]; then
+#     echo >&2 "$1:"
+#     for p in "${problems[@]}"
+#     do
+#       echo >&2 " * $p"
+#     done
+#     exit 1
+#   fi
+# }
 
 cycle() {
-    if [ -f "${DYNAMIC_COLORS_ROOT}/colorscheme" ]; then
-        current=`head -1 "${DYNAMIC_COLORS_ROOT}/colorscheme"`
+    if [ -f "$DYNAMIC_COLORS_THEMES" ]; then
+        current=`head -1 "$DYNAMIC_COLORS_THEMES"`
         found=false
-        cd "$COLORSCHEMES"
-        for file in *.sh; do
+        cd "$DYNAMIC_COLORS_THEMES"
+        for file in *; do
             if [ $found = true ]; then
-                switch "${file%.sh}"
+                switch "${file%}"
                 return
             fi
-            if [ $file = "${current}.sh" ]; then
+            if [ $file = "${current}" ]; then
                 found=true
             fi
         done
     fi
 
-    cd "$COLORSCHEMES"
-    for file in *.sh; do
-        switch "${file%.sh}"
+    cd "$DYNAMIC_COLORS_THEMES"
+    for file in *; do
+        switch "${file%}"
         break
     done
 }
 
 cycledown() {
-    if [ -f "${DYNAMIC_COLORS_ROOT}/colorscheme" ]; then
-        current=`head -1 "${DYNAMIC_COLORS_ROOT}/colorscheme"`
+    if [ -f "$DYNAMIC_COLORS_THEMES" ]; then
+        current=`head -1 "$DYNAMIC_COLORS_THEMES"`
         found=false
-        cd "$COLORSCHEMES"
-        for file in `ls -r *.sh`; do
+        cd "$DYNAMIC_COLORS_THEMES"
+        for file in `ls -r *`; do
             if [ $found = true ]; then
-                switch "${file%.sh}"
+                switch "${file%}"
                 return
             fi
             if [ $file = "${current}.sh" ]; then
@@ -173,41 +195,43 @@ cycledown() {
         done
     fi
 
-    cd "$COLORSCHEMES"
+    cd "$DYNAMIC_COLORS_THEMES"
     for file in `ls -r *.sh`; do
-        switch "${file%.sh}"
+        switch "${file%}"
         break
     done
 }
 
 list () {
-  [ ! -d "$COLORSCHEMES" ] && die "error: colorschemes directory '$COLORSCHEMES' doesn't exist"
-  cd "$COLORSCHEMES"
-  for file in *.sh; do
-    echo "${file%.sh}"
+  [ ! -d "$DYNAMIC_COLORS_THEMES" ] && die "error: colorschemes directory '$DYNAMIC_COLORS_THEMES' doesn't exist"
+  cd "$DYNAMIC_COLORS_THEMES"
+  for file in *; do
+    echo "$file"
   done
 }
 
-edit () {
-  cd "$COLORSCHEMES"
-  if [ ${#@} -eq 0 ]; then
-    ${EDITOR:-/usr/bin/vim} .
-  else
-    ${EDITOR:-/usr/bin/vim} "${@/%/.sh}"
-  fi
-}
+# TODO remove
+# edit () {
+#   cd "$DYNAMIC_COLORS_THEMES"
+#   if [ ${#@} -eq 0 ]; then
+#     ${EDITOR:-/usr/bin/vim} .
+#   else
+#     ${EDITOR:-/usr/bin/vim} "${@/%/.sh}"
+#   fi
+# }
 
-create () {
-  [ -f "$COLORSCHEMES/$1.sh" ] && die "error: colorscheme '$1' already exists"
-  output="# $1\n"
-  for color in ${colors[@]}; do
-    output+="\n$color=\"\""
-    [[ $color == color* ]] && output+=" # ${color_names[${color#color}]}"
-  done
-  cd "$COLORSCHEMES"
-  echo -e "$output" >> "$1.sh"
-  edit "$1"
-}
+# TODO remove
+# create () {
+#   [ -f "$COLORSCHEMES/$1.sh" ] && die "error: colorscheme '$1' already exists"
+#   output="# $1\n"
+#   for color in ${colors[@]}; do
+#     output+="\n$color=\"\""
+#     [[ $color == color* ]] && output+=" # ${color_names[${color#color}]}"
+#   done
+#   cd "$COLORSCHEMES"
+#   echo -e "$output" >> "$1.sh"
+#   edit "$1"
+# }
 
 usage () {
   die "$USAGE"
